### PR TITLE
Add racodon as developer in pom file

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
@racodond It is better for reviewing purposes to submit 1 rule per pull request

**Comment by dbolkensteyn** [comment]
@racodond That being said - perhaps you'd like to ask access to this CSS repository to maintain it together with @kalidasya ?

**Comment by racodond** [comment]
@dbolkensteyn: I am submitting one pull request per rule or task I'm doing. See all the open pull requests at https://github.com/SonarCommunity/sonar-css/pulls. I just create one branch from the previous branch for now because I want to avoid merge conflicts as the same files are updated. If you merge one pull request at a time starting from the oldest one, you'll be able to see the "real diff".

Yes, if @kalidasya is ok, you can give me access rights. I'll still proceed with pull request for my work to be reviewed before being merged.

**Comment by kalidasya** [comment]
@dbolkensteyn @racodond  Its fine by me, but I do not have the rights :(

**Comment by kalidasya** [comment]
and unfortunately after merge github still shows all commits not just the additions..

**Comment by dbolkensteyn** [comment]
@kalidasya Please send a request on the SonarQube Google Groups to grant the appropriate rights

**Comment by kalidasya** [comment]
@dbolkensteyn done

**Pull request merged**
