### PR TITLE
Fix grammar: SUP_DECLARATION, allow SEMICOLON first

### PR DESCRIPTION
**Pull request by racodond**
See also http://www.w3.org/TR/css3-syntax/#consume-a-list-of-declarations0

Please double-check as it is the first time I read and updated a grammar.

### CODE REVIEW

**Comment by kalidasya** [comment]
so it means something like:
a { color:red} is not valid?
also I think we parse now (or maybe we always did things like:
a {
color:red
background: none
}

**Comment by racodond** [comment]
`a { color:red}` is still valid with the updated grammar. I had tested the tweak of the grammar on my entire code base and the modification doesn't fire any additional parsing errors. I added some tests through https://github.com/racodond/sonar-css/commit/0db0812fa4b0d1ffa18a7aebddd7b45f967e9b9f

The below piece of code is indeed not valid CSS:
`a {
  color:red
  background: none
}`
But it was already successfully parsed with the previous version of the grammar. That was not good.

So, now the grammar is a little bit more accurate. But how could we fix `a {
  color:red
  background: none
}` should raise a parsing error?

**Comment by kalidasya** [comment]
ok I just realized what you did, so a sup declaration is a list of semicolons or declarations... 
you created a rule to use semicolon right? that should be ok for now I think. otherwise you have to handle this like (ignore casing) :
b.oneormore(b.sequence(declaration, b.nextnot(declaration), b.optional(semicolon)))
or 
 b.oneOrMore(b.firstOf(SEMICOLON, b.seqeunce(DECLARATION, b.nextnot(declaration))))

**Comment by racodond** [comment]
> ok I just realized what you did, so a sup declaration is a list of semicolons or declarations... 

Yes. It is how it was implemented.

> you created a rule to use semicolon right? that should be ok for now I think

=> Yes. But it doesn't fix the grammar issue :-) `a { color:red background: none }` should raise a parsing error. Moreover there won't be any issue on `background: none` because this node is not available in the AST. 

> b.oneormore(b.sequence(declaration, b.nextnot(declaration), b.optional(semicolon)))
> or 
> b.oneOrMore(b.firstOf(SEMICOLON, b.seqeunce(DECLARATION, b.nextnot(declaration))))

`b.oneOrMore(b.sequence(DECLARATION, b.nextNot(DECLARATION), b.optional(SEMICOLON)))` doesn't cover the following syntactically correct CSS code and raise a parsing error: `a { ;; }`

`b.oneOrMore(b.firstOf(SEMICOLON, b.sequence(DECLARATION, b.nextNot(DECLARATION))))` still doesn't cover `a { color:red background: none }`

Any other idea?

**Comment by kalidasya** [comment]
yes I see it now. there is no way to differentiate between a value and a next declaration....  a value can contain whitespace, and probably colon as well...

**Comment by racodond** [comment]
It's still very abstract to me but maybe, it shouldn't be `ANY` here but something a bit more restrictive, should it?

``` b.rule(VALUE).is(
      b.oneOrMore(b.firstOf(ANY, BLOCK, AT_KEYWORD)));
```

**Comment by kalidasya** [comment]
yes, but a lot of things are allowed there:
background: #ffffff url("img_tree.png") no-repeat right top;
this is the ANY. if we can find something what cannot be in a valid value (maybe the ':' ) but has to be in a 2nd declaration, we can create a rule for it and do b.nextNot(INVALID_DECLARATION)

**Comment by racodond** [comment]
I see. So for now, we can merge this one as it improves a lit bit the grammar on those corner cases of empty declarations (I found quite a few in our code base by the way). Also, I will create a rule to detect empty declarations.

**Comment by racodond** [comment]
Also, can we create a JIRA ticket about the grammar improvement to be thought to support `a { color:red background: none }`?

**Comment by kalidasya** [comment]
ok I merge this then.

**Pull request merged**
