### PR TITLE
Branch 1 11

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by kalidasya** [comment]
Hi @racodond , it seems this change introduced some coding issues:
https://nemo.sonarqube.org/component_issues?id=org.codehaus.sonar-plugins.css%3Acss#resolved=false|types=BUG

**Comment by kalidasya** [comment]
@racodond and can u take a look at the coverage numbers, https://nemo.sonarqube.org/component_measures/metric/coverage/tree?id=org.codehaus.sonar-plugins.css%3Acss we have a couple of untested class, not sure why

**Comment by racodond** [comment]
Hi @kalidasya ,

The 3 new issues have been fixed: https://github.com/SonarQubeCommunity/sonar-css/commit/fe3e653d230b6705b7b26adcb2147d01679e3828. The other one has been here from the beginning. I'll fix it when I refactor this class as it is deprecated.

What is reported as not covered are new objects of the Css Model: Css Elements and Validators. The issue come from SonarQube / JaCoCo that does not report cross module code coverage. Those Css Model Elements and Validators defined in the css-squid module are extensively (and only) used in the css-checks module. They are extensively tested through unit tests of the css-checks module but no coverage is reported on them because they are part of the css-squid module. I don't feel like moving those model objects to the css-checks module because they're not related to checks but more about grammar / tree building defined in the css-squid plugin. Later on they might be used by other modules as well.

**Comment by kalidasya** [comment]
@racodond yes, I was thinking more about the instanceof thing not the other issue, thats old, indeed. Great!

**Comment by racodond** [comment]
@kalidasya And here it is to get cross module code coverage taken into account: https://github.com/SonarQubeCommunity/sonar-css/commit/f5dec2a7e1c9f7167ff0e323d0bb02083f6194a1

It is now at 91.9% on my SonarQube local instance instead of 70.2%

**Comment by kalidasya** [comment]
@racodond great, thanks!!!

**Pull request merged**
