### PR TITLE
Add rule: fontface browser compatibility

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by kalidasya** [comment]
LGTM but the logic required to check it is quite a lot. Maybe we should do something in the grammar to get easier access to those url definitions?

**Comment by racodond** [comment]
I guess the best way would be to not longer browse the AST but add an abstraction layer on top of to work with objects. But I didn't get any feedback yet on https://groups.google.com/d/msg/sonarqube/7EtHCqNwXIg/MPT_oRVTBQAJ

**Comment by kalidasya** [comment]
And do you know does this strongly typed ast have any benefit, or what is the reason they moved to that way? to be honest I never got a response for that kind of question (I asked a similar one long ago about css and sass)

**Comment by racodond** [comment]
> what is the reason they moved to that way

I don't really know. But, from my point of view, adding this abstraction layer would make rules easier to write and understand. For now, you need to know how the AST is built to write rules. Instead of writing `node.getDescendant(xxx).getFirstChild(xxx)...`, it would be easier to write and understand: `selector.getProperties().get(0).getURL()...`. Also changes in the grammar, should not impact that upper abstraction layer. And I guess it would be mandatory when we start tackling Less or SASS. Otherwise we would have to provide three implementations for each rule: pure CSS, Less and SASS.

**Pull request merged**
