### PR TITLE
Issue 68 - Deal with case insensitivity of CSS grammar

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by kalidasya** [comment]
nice! but cannot merge. btw I dont think we need or use the baduri (badstring?) stuff

**Comment by racodond** [comment]
It looks like baduri stuff tries to avoid parsing issues when there's no closing parenthesis for example: url(blabla
I guess that we should let raise a parsing issue in those cases.
I'll do a bit of clean up and come back to you then.

**Comment by kalidasya** [comment]
yes the reason is that, but it is actually never used in the grammar I think.

**Comment by racodond** [comment]
Cleanup done and can now be merged

**Pull request merged**
